### ISSUE TITLE
estilos CSS

### ISSUE THREAD

**Issue by lokilaufeysonXD** [JaMR94/Front-End-ecommerce-UNID#31]
creo que debemos separar nuestros estilos e importarlos a nuestros archivos y asi nos evitamos ponerlos todos en el glovaly evitarnos conflictos 

creo que solo debemos poner en el gloval los estilos que son comunes esto deberiamos discutirlo

**Comment by kareng13** [comment]
Sabes como importar manualmente un archivo css que creemos? El global se conecta solito jaja
Atte: GerardoCasC

**Comment by abraham1669** [comment]
Es una excelente idea @lokilaufeysonXD genera mucho menos conflictos y no es tan complicado, les dejo la referencia desde la documentación y si tienen alguna duda de integración, me dicen
https://nextjs.org/docs/basic-features/built-in-css-support#adding-component-level-css

**Comment by Pudin-con-pasas-uwu** [comment]
ya esta, creo, disque una mini guía en mi pr para que la veas, es diferente a la documentación que subió el profe, pero creo que de igual manera funciona, por si es que te sirve

**Comment by lokilaufeysonXD** [comment]
la gia la pongo aqui para que quede 
![image](https://user-images.githubusercontent.com/55563474/223015110-9543b5cb-7970-4246-8072-970fc174b33a.png)

**Comment by lokilaufeysonXD** [comment]
ese metodo no me funciono pongo los pasos que hice 

1- Se crea un css con (nombre de tu css).module.css 
![image](https://user-images.githubusercontent.com/55563474/223015909-ca012c7e-d8b8-4acd-9cea-3c81168e26d2.png)

2- se importa la hoja de estilos  con import styles from 'localisacion de tu archivo css';
![image](https://user-images.githubusercontent.com/55563474/223016084-c469f681-f633-4ff4-b2f8-f7e29cbdc5ad.png)

3- se llama a la importacion donde vas a utilizarla ej className={styles. nombre de la classe}
![image](https://user-images.githubusercontent.com/55563474/223016405-1d96120e-3740-4bd2-800c-a62a4c016324.png)
![image](https://user-images.githubusercontent.com/55563474/223016695-9b855489-765b-4fbe-8609-fcc06c341c0c.png)

esta es la via que envio el profesor explicada
