### ISSUE TITLE
Header.

### ISSUE THREAD

**Issue by JaMR94** [JaMR94/Front-End-ecommerce-UNID#32]
Como cliente quisiera un header con pestañas de información, que me puedan llevar a los productos, información de la empresa, contacto, etc cuando lo necesite.
Ejemplo.
![Captura de pantalla 2023-03-04 214443](https://user-images.githubusercontent.com/123425046/222938927-4524dace-77c7-4013-98a4-4bfaacc624f0.png)

***

**Comment by lokilaufeysonXD** [comment]
el header ???????

**Comment by abraham1669** [comment]
Tienes que ser más descriptivo, puedes adjuntar capturas de pantalla o algo que nos permita saber qué tipo de header es o qué diseño se llevará a cabo
