### ISSUE TITLE
checar las carpas de las imágenes 

### ISSUE THREAD

**Issue by lokilaufeysonXD** [JaMR94/Front-End-ecommerce-UNID#33]
por favor chéquense en el proyecto hay dos carpetas una img y otra images porfa habría que dejar una 

![image](https://user-images.githubusercontent.com/55563474/222485373-47f2d74b-6645-4ccd-899d-70e0cfe8a959.png)

**Comment by abraham1669** [comment]
@JaMR94 revisa esto para darle seguimiento y saber si ya se completó o qué pasa

**Comment by Pudin-con-pasas-uwu** [comment]
ya esta listo, moví todo a una sola carpeta y elimine la que estaba de mas
