### ISSUE TITLE
acomodo de los componentes

### ISSUE THREAD

**Issue by Pudin-con-pasas-uwu** [JaMR94/Front-End-ecommerce-UNID#44]
no se si realmente sea necesario, pero creo que seria mas fácil y cómodo trabajar con los componentes dentro de sus respectivas carpetas, por ejemplo, todos los componentes de about us dentro de una carpeta llamada about o algo así.
![image](https://user-images.githubusercontent.com/71237346/222974523-91e45f2b-336b-42b5-9acb-6b2cf894e1e7.png)

**Comment by lokilaufeysonXD** [comment]
tienes razón
