### ISSUE TITLE
ayuda con codigo 

### ISSUE THREAD

**Issue by lokilaufeysonXD** [JaMR94/Front-End-ecommerce-UNID#74]
es para ver si alquien tiene save porque me da error a la hora de plasmar los datos de la API @abraham1669 
![image](https://user-images.githubusercontent.com/55563474/224569411-c429da09-baab-4226-a890-695786f89bee.png)
este es el componenete 
![image](https://user-images.githubusercontent.com/55563474/224569454-9166d931-259c-4040-9fc2-598758a393b6.png)
![image](https://user-images.githubusercontent.com/55563474/224569632-35bd8536-73e6-4b58-bd7f-487dfb317fe8.png)

**Comment by Creaky27** [comment]
Yo tengo una pregunta, ¿Quieres jalar la información de los productos o usuarios? y ¿Por qué usaste getInitialProps?

**Comment by lokilaufeysonXD** [comment]
para obtener datos iniciales para el componente antes de que se renderice en el lado del cliente pero ya quedo lo cheque con el profesor y quedo
